pipeline {
    agent any 
    environment {
        TOMCAT_USER = 'tomcat'      // Tomcat Manager username
        TOMCAT_PASS = 's3cret'  // Tomcat Manager password
        TOMCAT_URL = 'http://10.0.2.15:9090'  // Tomcat server URL
        WAR_FILE = '/var/lib/jenkins/workspace/simple-java/target/works-with-heroku-1.0.war'    // Path to the WAR file generated by Maven build...
        TOMCAT_DEPLOY_PATH = '/webapps'  // Tomcat deploy path (default is /webapps)
    }
    stages {
        stage('Build') {
            steps {
               echo "Building the application..."
               sh 'mvn clean package' 
            }
        }
   stage('Deploy to Tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: 'Tomcat_username_password', path: '', url: 'http://localhost:9090')], contextPath: null, war: '**/*.war'
            }
        }

    }
}
      
