pipeline {
    agent any 
    environment {
        TOMCAT_USER = 'tomcat'      // Tomcat Manager username
        TOMCAT_PASS = 's3cret'  // Tomcat Manager password
        TOMCAT_URL = 'http://10.0.2.15:9090'  // Tomcat server URL
        WAR_FILE = 'simple-java/target/works-with-heroku-1.0.war'    // Path to the WAR file generated by Maven build
        TOMCAT_DEPLOY_PATH = '/webapps'  // Tomcat deploy path (default is /webapps)
    }
    stages {
        stage('Build') {
            steps {
               echo "Building the application..."
               sh 'mvn clean package' 
            }
        }
   stage('Deploy to Tomcat') {
            steps {
                script {
                    // Option 1: Deploy using Tomcat Manager API
                    // Using curl to upload the WAR to Tomcat via the Manager API
                    sh """
                    curl --upload-file ${WAR_FILE} \
                        --user ${TOMCAT_USER}:${TOMCAT_PASS} \
                        ${TOMCAT_URL}/manager/html/webapps
                    """

                    // Option 2: Direct file copy to Tomcat (if Tomcat is running locally or has shared folder)
                    // sh """
                    // scp ${WAR_FILE} user@your-tomcat-server:/path/to/tomcat/webapps/
                    // """
                }
            }
        }

    }
}
      
